# Generated by Django 6.0.4 on 2026-04-19 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products_image')),
                ('price', models.IntegerField()),
                ('is_spare_part', models.BooleanField(default=False)),
                ('is_machinery', models.BooleanField(default=False)),
                ('is_power_tools', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='BurhaniApp.category')),
            ],
        ),
    ]
