# Generated by Django 6.0.4 on 2026-04-20 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurhaniApp', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_quantity',
            new_name='bill',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField()),
                ('product_total', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BurhaniApp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BurhaniApp.product')),
            ],
        ),
    ]
