# Generated by Django 6.0.4 on 2026-05-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurhaniApp', '0010_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gst_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_qty',
            field=models.IntegerField(default=0),
        ),
    ]
