# Generated by Django 6.0.4 on 2026-09-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurhaniApp', '0012_productvideo'),
        ('BurhaniApp', '0014_alter_payment_payment_date_and_more'),
    ]

    operations = [
    ]
